---
version: "3"

services:
  traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=${ACME_ENABLE}"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
        # Enable for staging
      - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always
    networks:
      - primero
    volumes:
      - "${ACME_STORAGE_PATH}:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  couchdb:
    image: "jozian/couchdb:latest"
    container_name: "couchdb"
    restart: always
    networks:
      - primero
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    ports:
      - "4369:4369"
      - "5984:5984"
      - "6984:6984"
      - "9100:9100"
    volumes:
      - "${COUCHDB_DATA_PATH}:/opt/couchdb/data"
      - "${COUCHDB_LOG_PATH}:/opt/couchdb/log"
      - "${COUCHDB_CONFIG_PATH}:/opt/couchdb/etc/local.d"

  solr:
    image: "solr:5"
    container_name: "solr"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - ${RAILS_ENV}
      - /opt/solr/server/solr/configsets/primero
    restart: always
    networks:
      - primero
    ports:
      - "8983:8983"
    volumes:
      - "${SOLR_PRIMERO_CONFIGSET_PATH}:/opt/solr/server/solr/configsets/primero"
      - "${SOLR_CORE_PATH}:/opt/solr/server/solr/mycores"

  beanstalk:
    image: jozian/beanstalkd:latest
    container_name: beanstalk
    restart: always
    networks:
      - primero
    ports:
      - "11300:11300"
    volumes:
      - "${BEANSTALKD_BINLOG_PATH}:/var/lib/beanstalkd"

networks:
  primero:
    external: true
