---
version: '3'
services:
  postgres:
    image: postgres:prim-latest
    volumes:
      - log:/var/log/postgresql
      - database:/var/lib/postgresql/data
    env_file:
      - docker/defaults.env
  solr:
    image: solr:prim-latest
    env_file:
      - docker/defaults.env
    volumes:
      - solr_cores:/opt/solr/server/solr/mycores
  beanstalkd:
    image: beanstalkd:prim-latest
    env_file:
      - docker/defaults.env
volumes:
  database:
  local_certs:
  certbot_var:
  certbot_etc:
  tmp:
  log:
  public:
  solr_cores:
