---
version: '3'
services:
  application:
    image: application:prim-latest
    depends_on:
      - solr
      - beanstalkd
      - postgres
    volumes:
      - log:/srv/primero/application/log
      - public:/srv/primero/application/public
      - tmp:/srv/primero/application/tmp
    env_file:
      - docker/defaults.env
      - docker/quoin.env
      - docker/local.env
    stdin_open: true
    tty: true
  nginx:
    image: nginx:prim-latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - local_certs:/etc/certs
      - tmp:/srv/primero/application/tmp
      - log:/var/log/nginx
      - public:/srv/primero/application/public
    env_file:
      - docker/defaults.env
      - docker/local.env
      - docker/quoin.env
    depends_on:
      - application
  solr:
    env_file:
      - docker/defaults.env
      - docker/local.env
      - docker/quoin.env
  beanstalkd:
    env_file:
      - docker/defaults.env
      - docker/local.env
      - docker/quoin.env
  postgres:
    env_file:
      - docker/defaults.env
      - docker/local.env
      - docker/quoin.env
